# Kubernetes Deployment + Service + Ingress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitcode-api
  namespace: production
  labels:
    app: gitcode-api
    version: v2.4.0
    team: platform
  annotations:
    deployment.kubernetes.io/revision: "12"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gitcode-api
  template:
    metadata:
      labels:
        app: gitcode-api
        version: v2.4.0
    spec:
      serviceAccountName: gitcode-api
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: registry.example.com/gitcode/api:v2.4.0
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gitcode-db-credentials
                  key: url
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: gitcode-config
                  key: redis-host
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /etc/gitcode
              readOnly: true
        - name: sidecar-logger
          image: registry.example.com/fluentbit:2.2
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/app
      volumes:
        - name: config-volume
          configMap:
            name: gitcode-config
        - name: shared-logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitcode-api
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gitcode-api
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitcode-api
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.gitcode.example.com
      secretName: gitcode-api-tls
  rules:
    - host: api.gitcode.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitcode-api
                port:
                  number: 80
